---

root: true

env:
  browser: true
  mocha: true
  node: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    generators: true
    experimentalObjectRestSpread: true

plugins:
  - react

rules:
  block-spacing: [2, always]
  brace-style: [2, 1tbs]
  comma-dangle: 0
  curly: [2, all]
  eqeqeq: 2
  indent: [2, tab]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  keyword-spacing: [2, {before: true, after: true}]
  linebreak-style: [2, unix]
  no-console: 0
  no-control-regex: 0
  no-inner-declarations: 2
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-trailing-spaces: 2
  no-unexpected-multiline: 2
  no-unreachable: 2
  object-curly-spacing: [2, never]
  quotes: [2, double, avoid-escape]
  semi: [2, always]
  space-before-blocks: 2
  space-infix-ops: 2
  spaced-comment: [2, always]
  react/jsx-equals-spacing: [2, never]
  react/jsx-no-duplicate-props: [2, {ignoreCase: true}]
  react/jsx-no-undef: 2
  react/jsx-pascal-case: [2, {allowAllCaps: true, ignore: []}]
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/no-deprecated: 2
  react/no-direct-mutation-state: 2
  react/no-is-mounted: 2
  react/react-in-jsx-scope: 2
  react/require-render-return: 2
  react/jsx-space-before-closing: [2, always]
  react/jsx-indent: [2, tab]
  react/jsx-indent-props: [2, tab]
  react/jsx-first-prop-new-line: [2, multiline]
  react/jsx-curly-spacing: [2, never]
  react/jsx-closing-bracket-location: 2

globals:
  log: false
  $: false
  Favico: false
  Handlebars: false
  io: false
  Mousetrap: false

extends: eslint:recommended
